### ISSUE TITLE
Run a new test with  checkov:latest

### ISSUE THREAD

**Issue by ismailyenigul** [iacsecurity/tool-compare#16]
Can you please re-run checks for checkov. There are some updates on checks.
Also that would be great if you can add Last Scan time to the readme to see when it is executed.

**Comment by yi2020** [comment]
Ran:
* ` find . -name "checkov_results.txt" -exec rm {} \;`
* Checkov latest (copied from `run_all_tools.sh`):
```
docker pull bridgecrew/checkov:latest
docker run -t -v $PWD:/tf bridgecrew/checkov --version > version_checkov.txt
find . -name "main.tf" -exec dirname {} \; | grep -v "\.terraform" | while read -r test_case; do echo $test_case ; ORG_PATH=$PWD ; cd $test_case ; if [ ! -f checkov_results.txt ]; then docker run -t -v $PWD:/tf bridgecrew/checkov --quiet -d /tf | sed 's/[[0-9;]*m//g' | sed "s~$ORG_PATH~tool-compare~" > checkov_results.txt ; fi ; cd $ORG_PATH; done
```

@ismailyenigul notice that the command execution has a `sed` in it to remove control characters from the output. The newer version of Checkov all of a sudden introduced another control character (see changes in PR #17 ). Any idea what changed in recent versions and how to turn this off? I can expand the sed command, but there's probably a path that makes more sense.

**Comment by yi2020** [comment]
Hmmm... it's not possible to see the weird control characters in the GitHub view. Here's a screenshot of how it looks like in PyCharm:
<img width="1203" alt="Screen Shot 2021-05-10 at 3 03 53 PM" src="https://user-images.githubusercontent.com/10076447/117730261-f1876c80-b1a0-11eb-9d4f-adc3d4ceb3c7.png">

Appreciate your help in finding a way for Checkov not to add these.

**Comment by ismailyenigul** [comment]
It seems `-t` docker  flag causes that issue. The output is fine without it.
