### ISSUE TITLE
Update instance type for ebs optimized

### ISSUE THREAD

**Issue by owenrumney** [iacsecurity/tool-compare#22]
I was looking at the [ebs optimized check](https://github.com/iacsecurity/tool-compare/tree/main/test-cases/terraform/aws/best-practices/ec2_ebs_not_optimized) and noticed that the instance type used has EBS as optimized. the instances that support but don't have default are;

c1.xlarge
c3.xlarge
c3.2xlarge
c3.4xlarge
g2.2xlarge
i2.xlarge
i2.2xlarge
i2.4xlarge
m1.large
m1.xlarge
m2.2xlarge
m2.4xlarge
m3.xlarge
m3.2xlarge
r3.xlarge
r3.2xlarge
r3.4xlarge

https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ebs-optimized.html

**Comment by yi2020** [comment]
Good catch, feel free to open a PR to fix it.
