### ISSUE TITLE
Inaccurate comparison between tools?

### ISSUE THREAD

**Issue by schosterbarak** [iacsecurity/tool-compare#44]
looks like some of the tools are being executed on the "plan" phase while others directly on the IaC files?
Is the comparison been done only for terraform? Some of the tools support multiple IaC

**Comment by yi2020** [comment]
Those are great questions:
1. Some tools only support scanning the plan, while some support only the code files (AFAIK), and some support both. So I went for the option of using the plan where possible as it should generate more precise results.
2. I wanted to add more IaC (like CFN), as well as more cloud environments (like Azure and GCP). I didn't have the bandwidth to do it yet and would appreciate help of course :)

One more thing, @christophetd and I did start working on adding high-level tool information (like features and languages supported), but haven't completed it yet. Help there would also be great.

**Comment by schosterbarak** [comment]
1. cool. Checkov support both.

**Comment by yi2020** [comment]
1. Is there any benefit to using the code files with checkov over plan? I thought the plan would be the better option so used that.

**Comment by schosterbarak** [comment]
https://bridgecrew.io/blog/terraform-plan-security-scanning-checkov/
