### ISSUE TITLE
Snyk now supports custom policies written in rego

### ISSUE THREAD

**Issue by dharada1** [iacsecurity/tool-compare#52]
But it's still in beta status.
Can I just change Custom Rule Support - Snyk cell into "yes" ?

https://snyk.io/blog/developing-custom-iac-rules-with-snyk-iac/
https://docs.snyk.io/products/snyk-infrastructure-as-code/custom-rules

**Comment by yi2020** [comment]
@dharada1 go ahead and submit a PR
