### ISSUE TITLE
rds_retention_period_set should check  preferred_backup_window or backup_retention_period or both?

### ISSUE THREAD

**Issue by rajlearner17** [iacsecurity/tool-compare#55]
https://github.com/iacsecurity/tool-compare/blob/main/test-cases/terraform/aws/best-practices/rds_retention_period_set/main.tf

This is related to r[ds_retention_period_set](https://github.com/iacsecurity/tool-compare/tree/main/test-cases/terraform/aws/best-practices/rds_retention_period_set)

the **main.tf** specifies to check `preferred_backup_window`

```
resource "aws_rds_cluster" "default" {
  cluster_identifier      = "aurora-cluster-demo"
  engine                  = "aurora-mysql"
  engine_version          = "5.7.mysql_aurora.2.03.2"
  availability_zones      = ["us-west-2a", "us-west-2b", "us-west-2c"]
  database_name           = "mydb"
  master_username         = "foo"
  master_password         = "bar"
  preferred_backup_window = "07:00-09:00"
}
```

should not it check `backup_retention_period` ?

```
resource "aws_rds_cluster" "rds_cluster_2" {
  cluster_identifier      = "demo"
  engine                  = "aurora-postgresql"
  availability_zones      = ["us-west-2a", "us-west-2b", "us-west-2c"]
  database_name           = "mydb"
  master_username         = "foo"
  master_password         = "bar"
  backup_retention_period = 5
  preferred_backup_window = "07:00-09:00"
  enabled_cloudwatch_logs_exports = ["audit", "error"]
}
```

I may be wrong, pls correct me.

**Comment by yi2020** [comment]
@rajlearner17 the test case is supposed to simulate a situation where there wasn't an specific retention period defined. That is, the TF code does not contain any specific value, and the default is used. So the test case is correct.
